steps:
- name: gcr.io/cloud-builders/docker
  args: ["build", "-f", "Dockerfile", "-t", "asia.gcr.io/$PROJECT_ID/ml-app:${TAG_NAME}", "."]

- name: gcr.io/cloud-builders/docker
  args: ["push", "asia.gcr.io/$PROJECT_ID/ml-app:${TAG_NAME}"]