steps:
- name: 'ubuntu'
  args:
    - bash
    - -c
    - 'rm -rf .dockeringnore && echo $TAG_NAME'
  id: 'rm-dockerignore'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - if
    - Dockerfile
    - --tag
    - asia.gcr.io/$PROJECT_ID/ml-app:$TAG_NAME
    - .
  waitFor: ['rm-dockerignore']

- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - asia.gcr.io/$PROJECT_ID/ml-app:$TAG_NAME
