---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-app-2
  template:
    metadata:
      labels:
        app: ml-app-2
    spec:
      containers:
      - name: ml-app-2
        # image: public.ecr.aws/q7x2l2d4/ml-demo:0.3
        image: asia.gcr.io/direct-plateau-322502/ml-app:0798ace1f3a4498882eb72c54c5f48d156e5173a
        ports:
        - containerPort: 80
        command: ["/bin/sh", "-c"]
        args: 
          - git clone https://github.com/m0ttai/ml-demo.git;
            python /ml-demo/ml/animal_predict2.py;
        volumeMounts:
          - mountPath: /config
            name: config-volume
        env:
        - name: POD_IP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      volumes:
        - name: config-volume
          secret:
            secretName: credential2

---
apiVersion: v1
kind: Service
metadata:
  name: ml-lb-2
spec:
  type: LoadBalancer
  selector:
    app: ml-app-2
  ports:
  - name: "http"
    protocol: "TCP"
    port: 10080
    targetPort: 80