apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-app
  template:
    metadata:
      labels:
        app: ml-app
    spec:
      containers:
      - name: ml-app
        image: public.ecr.aws/q7x2l2d4/ml-demo:latest
        ports:
        - containerPort: 80
        command: ["/bin/sh", "-c"]
        args: 
          - git clone https://github.com/m0ttai/ml-demo.git;
            python /ml-demo/ml/animal_predict2.py;
        env:
        - name: POD_IP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP